### PR TITLE
Update AbstractLoadBefore.php

### PR DESCRIPTION
**Pull request by aholovan**
Some bugfixes and improvements

### CODE REVIEW

**Review by aholovan — COMMENTED** [review]
Please, review

**Comment by YehorShytikovWB** [comment]
sounds good

**Comment by Genaker** [comment]
> Please, review

Merged please test if you have Magento. 

I have another way to implement this check.

**Comment by aholovan** [comment]
@Genaker, 
Hi, that patch already works on some production sites at least month - no errors. Thanks for adding any improvements!

**Pull request merged**
